locallibary/catalog/urls.py
from django.urls    import path
from .              import views

urlpatterns = [
    path('', views.index, name='index'),
    path('items/', views.ItemListView.as_view(),name='items'),
    path('item/<int:pk>', views.ItemDetailView.as_view(), name='item-detail'),
    path('store/', views.StoreListView.as_view(),name='store'),
    path('store/<int:pk>', views.StoreDetailView.as_view(), name='store-detail'),
    path('myitems/', views.UsersItemsByListView.as_view(), name='my-items'),
    path('item/<uuid:pk>/renew/', views.renew_item, name='renew-item'),
    path('store/create/', views.StoreCreate.as_view(), name='store-create'),
    path('store/<int:pk>/update/', views.StoreUpdate.as_view(), name='store-update'),
    path('store/<int:pk>/delete/', views.StoreDelete.as_view(), name='store-delete'),
    path('item/create/', views.ItemCreate.as_view(), name='item-create'),
    path('item/<int:pk>/update/', views.ItemUpdate.as_view(), name='item-update'),
    path('item/<int:pk>/delete/', views.ItemDelete.as_view(), name='item-delete'),
]

locallibary/locallibary/urls.py
from django.contrib             import admin
from django.urls                import path, include
from django.views.generic       import RedirectView
from django.conf                import settings
from django.conf.urls.static    import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('catalog/', include('catalog.urls')),
    path('', RedirectView.as_view(url='catalog/',permanent=True)), 
    path('accounts/', include('django.contrib.auth.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

locallibary/catalog/models.py
from django.contrib.auth.models     import User
from django.db                      import models
from django.urls                    import reverse 
from datetime                       import date
import uuid       


################ITEM###############################
class Item(models.Model):
    #Model representing a item (but not a specific Item).
    title = models.CharField(max_length=200)

    store = models.ForeignKey('Store', on_delete=models.SET_NULL, null=True)

    summary = models.TextField(max_length=1000, help_text='Enter a description of Item ')

    def __str__(self):
        #String for representing the Model object.
        return self.title

    def get_absolute_url(self):
        """Returns the URL to access a detail record for this item."""
        return reverse('item-detail', args=[str(self.id)])

class ItemInstance(models.Model):
    #Model representing a specific item 
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, help_text='Unique ID for this particular Item across whole Store')
    item = models.ForeignKey('Item', on_delete=models.RESTRICT, null=True)
    imprint = models.CharField(max_length=200)
    due_back = models.DateField(null=True, blank=True)

    #To see if item is available
    LOAN_STATUS = (
        ('m', 'Maintenance'),
        ('o', 'Refiling soon'),
        ('a', 'Available'),
        ('r', 'Out of item'),
    )

    status = models.CharField(
        max_length=1,
        choices=LOAN_STATUS,
        blank=True,
        default='m',
        help_text='Item status',
    )
    got_item = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)

    @property
    def is_overdue(self):
    #Determines if item need to be renewed 
        return bool(self.due_back and date.today() > self.due_back)


    class Meta:
        ordering = ['due_back']
        permissions = (("can_mark_renewed", "Set Item as renewed"),)

    def __str__(self):
        #String for representing the Model object.
        return f'{self.id} ({self.item.title})'

#################STORE###############################

class Store(models.Model):
    #Model representing an store.
    compeny_name = models.CharField(max_length=100, help_text='Enter a compeny name', default=' ')
    type_name = models.CharField(max_length=100, help_text='Enter a type name', default=' ')
    class Meta:
        ordering = ['type_name', 'compeny_name']

    def get_absolute_url(self):
        #Returns the URL to access a particular store instance.
        return reverse('store-detail', args=[str(self.id)])

    def __str__(self):
        #String for representing the Model object.
        return f'{self.compeny_name}, {self.type_name}'

locallibary/catalog/forms.py
from django                     import forms
from django.core.exceptions     import ValidationError
from django.utils.translation   import gettext_lazy as _
import datetime

class RenewItemForm(forms.Form):
    renewal_date = forms.DateField(help_text="Enter a date between now and 4 weeks.")

    def clean_renewal_date(self):
        data = self.cleaned_data['renewal_date']

        # Check if its inn the past.
        if data < datetime.date.today():
            raise ValidationError(_('Invalid date - renewal in past'))

        # Check if a date is after 4 weeks.
        if data > datetime.date.today() + datetime.timedelta(weeks=4):
            raise ValidationError(_('Invalid date - renewal more than 4 weeks ahead'))

        #clean data.
        return data

locallibary/catalog/views.py
from django.shortcuts                   import render
from .models                            import Item, Store, ItemInstance
from django.views                       import generic
from django.contrib.auth.mixins         import LoginRequiredMixin
from django.contrib.auth.decorators     import login_required, permission_required
from django.shortcuts                   import get_object_or_404
from django.http                        import HttpResponseRedirect
from django.urls                        import reverse
from catalog.forms                      import RenewItemForm
from django.views.generic.edit          import CreateView, UpdateView, DeleteView
from django.urls                        import reverse_lazy
import datetime


def index(request):
    #View home page of site.

    # Generate counts of some of the main objects
    num_items = Item.objects.all().count()
    num_instances = ItemInstance.objects.all().count()

    # Available items (status = 'a')
    num_instances_available = ItemInstance.objects.filter(status__exact='a').count()

    # The 'all()' is implied by default.
    num_store = Store.objects.count()

    context = {
        'num_items': num_items,
        'num_instances': num_instances,
        'num_instances_available': num_instances_available,
        'num_store': num_store,
    }

    # Render the HTML template index.html with the data in the context variable
    return render(request, 'index.html', context=context)

class ItemListView(generic.ListView):
    model = Item 
    paginate_by = 100
class ItemDetailView(generic.DetailView):
    model = Item
    

class StoreListView(generic.ListView):
    model = Store
    paginate_by = 200
class StoreDetailView(generic.DetailView):
    model = Store

def index(request):
    # …

    num_stores = Store.objects.count()  # The 'all()' is implied by default.
    num_items = Item.objects.count()
    # Number of visits to this view, as counted in the session variable.
    num_visits = request.session.get('num_visits', 0)
    request.session['num_visits'] = num_visits + 1

    context = {
        'num_items': num_items,
        'num_stores': num_stores,
        'num_visits': num_visits,
    }

    # Render the HTML template index.html.
    return render(request, 'index.html', context=context)


class UsersItemsByListView(LoginRequiredMixin,generic.ListView):
    model = ItemInstance
    template_name ='catalog/iteminstance_list_got_item_user.html'
    paginate_by = 10

    def get_queryset(self):
        return ItemInstance.objects.filter(got_item=self.request.user).filter(status__exact='o').order_by('due_back')



@login_required
@permission_required('catalog.can_mark_returned', raise_exception=True)
def renew_item(request, pk):
    
    item_instance = get_object_or_404(ItemInstance, pk=pk)

    if request.method == 'POST':

        form = RenewItemForm(request.POST)

        # Check if the form is valid
        if form.is_valid():
            # process the data in form.cleaned_data as required 
            item_instance.due_back = form.cleaned_data['renewal_date']
            item_instance.save()

            # redirect to a new URL:
            return HttpResponseRedirect(reverse('all-items-you-have'))

    
    else:
        proposed_renewal_date = datetime.date.today() + datetime.timedelta(weeks=3)
        form = RenewItemForm(initial={'renewal_date': proposed_renewal_date})

    context = {
        'form': form,
        'item_instance': item_instance,
    }

    return render(request, 'catalog/item_renew_item.html', context)

#############RE-STORES##################
class StoreCreate(CreateView):
        model = Store
        fields = ['type_name', 'compeny_name']

class StoreUpdate(UpdateView):
    model = Store
    fields = '__all__' # potential security issue if more fields added

class StoreDelete(DeleteView):
    model = Store
    success_url = reverse_lazy('store')
    

############RE-ITEMS#####################
class ItemCreate(CreateView):
        model = Item
        fields = ['title','store','summary']

class ItemUpdate(UpdateView):
    model = Item
    fields = '__all__' # potential security issue if more fields added

class ItemDelete(DeleteView):
    model = Item
    success_url = reverse_lazy('items')

locallibary/catalog/templates/catalog/item_comfirm_delete.html
{% extends "base_generic.html" %}

{% block content %}

<h1>Delete store</h1>

<p>Are you sure you want to delete the store: {{ store }}?</p>

<form action="" method="POST">
  {% csrf_token %}
  <input type="submit" value="Yes, delete.">
</form>

{% endblock %}

locallibary/catalog/templates/catalog/item_confirm_delete.html
{% extends "base_generic.html" %}

{% block content %}

<div class="card text-white bg-danger mb-3" style="max-width: 18rem;">
  <div class="card-header">Delete</div>
  <div class="card-body">
    <h5 class="card-title">Delete item</h5>
    <p class="card-text">Are you sure you want to delete the item: {{ item }}?</p>
  </div>
<form action="" method="POST">
  {% csrf_token %}
  <input type="submit" value="Yes, delete.">
</form>

{% endblock %}

locallibary/catalog/templates/catalog/item_detail.html
{% extends "base_generic.html" %}

{% block content %}
  <h1>Item: {{ item.title }}</h1>

  <p><strong>Store:</strong> <a href="">{{ item.store }}</a></p> <!-- store detail link not yet defined -->
  <p><strong>Summary:</strong> {{ item.summary }}</p>

  <p><strong>Do you want to update this item</strong></p>
  <button><a href="{% url 'item-update' item.id %}">Yes, update item</a></button>
  <br></br>

  <p><strong>Do you want to delete this Item</strong></p>
  <button><a href="{% url 'item-delete' item.id %}">Yes, delete item</a></button>
  <div style="margin-left:20px;margin-top:20px">
    {% for copy in item.iteminstance_set.all %}
      <hr>
      <p class="{% if copy.status == 'a' %}text-success{% elif copy.status == 'm' %}text-danger{% else %}text-warning{% endif %}">
        {{ copy.get_status_display }}
      </p>
      {% if copy.status != 'a' %}
        <p><strong>Due to be restored:</strong> {{ copy.due_back }}</p>
      {% endif %}
      <p class="text-muted"><strong>Id:</strong> {{ copy.id }}</p>
    {% endfor %}
  </div>
{% endblock %}
<div class="container-fluid">
  <div class="row">
    <div class="col-sm-2">
    {% block sidebar %}
      <ul class="sidebar-nav">
    
       {% if user.is_authenticated %}
        <li>User: {{ user.get_username }}</li>
        <li><a href="{% url 'index' %}">Home</a></li>
        <li><a href="{% url 'items' %}">All items</a></li>
        <li><a href="{% url 'store' %}">All stores</a></li>
        <li><a href="{% url 'item-create' %}?next={{request.path}}">add item</a></li>
        <li><a href="{% url 'store-create' %}?next={{request.path}}">add store</a></li>
        <li><a href="{% url 'logout'%}?next={{request.path}}">Logout</a></li>
       {% else %}
         <li><a href="{% url 'login'%}?next={{request.path}}">Login</a></li>
       {% endif %}
      </ul>
   {% endblock %}
  </div>

locallibary/catalog/templates/catalog/item_form.html
{% extends "base_generic.html" %}

{% block content %}
  <form action="" method="post">
    {% csrf_token %}
    <table>
    {{ form.as_table }}
    </table>
    <input type="submit" value="Submit">
  </form>
{% endblock %}

locallibary/catalog/templates/catalog/item_list.html
{% extends "base_generic.html" %}

{% block content %}
  <h1>Item List</h1>
  {% if item_list %}
  <div class="card" style="width: 18rem;">
    <ul class="list-group list-group-flush">
    {% for item in item_list %}
      <li>
        <a href="{{ item.get_absolute_url }}">{{ item.title }}</a> ({{item.store}})
      </li>
    {% endfor %}
    </ul>
  </div>
  {% else %}
    <p>There are no items in this store</p>
  {% endif %}
{% endblock %}

locallibary/catalog/templates/catalog/item_renew_item.html
{% extends "base_generic.html" %}

{% block content %}
  <h1>Renew: {{ item_instance.item.title }}</h1>
  <p>Borrower: {{ item_instance.borrower }}</p>
  <p{% if item_instance.is_overdue %} class="text-danger"{% endif %}>Due date: {{ item_instance.due_back }}</p>
  <form action="" method="post">
    {% csrf_token %}
    <table>
    {{ form.as_table }}
    </table>
    <input type="submit" value="Submit">
  </form>
{% endblock %}

locallibary/catalog/templates/catalog/iteminstance_list_got-item_user.html
{% extends "base_generic.html" %}

{% block content %}
    <h1>Items you have</h1>

    {% if iteminstance_list %}
    <ul>

      {% for iteminst in iteminstance_list %}
      <li class="{% if iteminst.is_overdue %}text-danger{% endif %}">
        <a href="{% url 'item-detail' iteminst.item.pk %}">{{iteminst.item.title}}</a> ({{ iteminst.due_back }})
      </li>
      {% endfor %}
    </ul>

    {% else %}
      <p>There are no items that you have.</p>
    {% endif %}
{% endblock %}

locallibary/catalog/templates/catalog/iteminstance_list_got_item_user.html
{% extends "base_generic.html" %}

{% block content %}
    <h1>Items you have</h1>

    {% if iteminstance_list %}
    <ul>

      {% for iteminst in iteminstance_list %}
      <li class="{% if iteminst.is_overdue %}text-danger{% endif %}">
        <a href="{% url 'item-detail' iteminst.item.pk %}">{{iteminst.item.title}}</a> ({{ iteminst.due_back }})
      </li>
      {% endfor %}
    </ul>

    {% else %}
      <p>There are no items that you have.</p>
    {% endif %}
{% endblock %}

locallibary/catalog/templates/catalog/store_detail.html
{% extends "base_generic.html" %}

{% block content %}
  <h1>store: {{ store.compeny_name  }}</h1>
  <p><strong>type of store:</strong> {{ store.type_name }}</p>

  <p><strong>Do you want to update this store</strong></p>
  <button><a href="{% url 'store-update' store.id %}">Yes, update store</a></button>
  <br></br>
  <p><strong>Do you want to delete this store</strong></p>
  <button><a href="{% url 'store-delete' store.id %}">Yes, delete store</a></button>

  <div style="margin-left:20px;margin-top:20px">
    {% for copy in item.iteminstance_set.all %}
      <hr>
      <p class="{% if copy.status == 'a' %}text-success{% elif copy.status == 'm' %}text-danger{% else %}text-warning{% endif %}">
        {{ copy.get_status_display }}
      </p>
      {% if copy.status != 'a' %}
        <p><strong>Due to be restokked:</strong> {{ copy.due_back }}</p>
      {% endif %}
      <p class="text-muted"><strong>Id:</strong> {{ copy.id }}</p>
    {% endfor %}
  </div>
{% endblock %}
<div class="container-fluid">
  <div class="row">
    <div class="col-sm-2">
    {% block sidebar %}
      <ul class="sidebar-nav">
    
       {% if user.is_authenticated %}
        <li>User: {{ user.get_username }}</li>
        <li><a href="{% url 'index' %}">Home</a></li>
        <li><a href="{% url 'items' %}">All items</a></li>
        <li><a href="{% url 'store' %}">All stores</a></li>
        <li><a href="{% url 'item-create' %}?next={{request.path}}">add item</a></li>
        <li><a href="{% url 'store-create' %}?next={{request.path}}">add store</a></li>
        <li><a href="{% url 'logout'%}?next={{request.path}}">Logout</a></li>
       {% else %}
         <li><a href="{% url 'login'%}?next={{request.path}}">Login</a></li>
       {% endif %}
      </ul>
   {% endblock %}
  </div>

locallibary/catalog/templates/catalog/store_form.html
{% extends "base_generic.html" %}

{% block content %}
  <form action="" method="post">
    {% csrf_token %}
    <table>
    {{ form.as_table }}
    </table>
    <input type="submit" value="Submit">
  </form>
{% endblock %}

locallibary/catalog/templates/catalog/store_list.html
{% extends "base_generic.html" %}

{% block content %}
  <h1>Store list</h1>
  {% if store_list %}
  <div class="card" style="width: 18rem;">
  <ul class="list-group list-group-flush">
    {% for store in store_list %}
      <li>
        <a href="{{ store.get_absolute_url }}">{{ store.compeny_name }}</a>
      </li>
    {% endfor %}
  </ul>
  {% else %}
    <p>There are no items in this store</p>
  {% endif %}
{% endblock %}